trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:qweASD123@tcp(192.168.101.236:3306)/testdb?parseTime=True
  redis:
    addr: 192.168.101.236:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
